version: '3'

services:
  reservations_module:
    build: .
    depends_on:
      - db
    ports:
      - '3020:3020'

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'reservations'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: